language: r
cache: packages
pandoc_version: 2.9.2.1

env:
  global:
    secure: "vP/dnJ5Z2/LsCXB4EoB8JgECfsevGOKbxrV2ypZDY2zSxO6Kzj/SvAqVeT9SyeL1ozpnpJMmBXjtupx2qEhpnib/GuPAEx9KUfU/9E9lWqDTiu0NhvyOoMfpTnshuhgOiuv9XF5chB+XEeWYN4Tebozg4y7jgPl1aSEZcbpQxX/4atJ20faPbzb5mbkpRrQexESVzbPj8a7MuflW2XyTD5Jp6pwZsWAPH4AkXTil7d07IRUcPQNPibPjWPcu+gSa3ZWrHXjf5r2a2Y99t8j5r3qH6pk64irSLlBrz7YFV4PTOAJYyaiMGuLfeSjjmGkgEoQ/FHQRGBJ9TXOPJry7XIkcDlDAmFdk23wDsH6oomDEIBtAEJlh+js1sfKI2Ub6umqUEXOpx/iHTtES36vnJl0PoJzQZbaHg6+BD1R5Eu4Q4lLXQc1vHgzVPqNXIJAwkq0LJKoPrXHWhtwpuqn7ja7qPmGox3TcVtlop21qgPBJfC4MssuJMnq5WMfVvQ8s2DjdacUEkeKGs6kEAOXnqY/V1ATAv6qMf1MWg2SRL5O5Lx8eINRFlx8XcF9oC5pej/vPNf//hp6VGsdexb/jpK8R0W+Aexf6qyE6JVee0HEqXje0jmmdPwI8rSTmsGH+dixAGe7tYTNXTmr25CqlRjlt3vhXXUcaOoz1LyKJ+tc="

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
