language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

secure: "WU6+vW/8IyPPjSnHQ9Zep4vdzOfC8bnVsd63zjl0skdklFAGiF5ia45BlrjqZ+D2rKjnAqBV/KtuJvBGYmXhpeFeaF+i3lyJuJ/420+ghnvPHI0ZjnVPOABwWjauutchYQdDpO5LoZugmdTSKs9TUlJaxHpfCgoybid7jg1veAyUcF8VgvYuOSgxRgzO64DV0OBcn6EX3OGJPNucEsSfTYOpOOrSosgvxnNfm0eHIPTeKXD3+35tVN7sdAGFJbG6nxSPIMmMI9mukBW6riaDoWw3hHoAanBcft8IMOZVZh9XTjkED3hQAAp3NVlm75puzQ6n9GYlKjtPOHAk1UBwm6JcJd2/QLS7WRA1+emQ6rTi+Iv88b3hFZInH6OyHFJ4BHCg8nS5ITgrSXL6iBfXwkqzAWDSS1dx6oVbikUQBTqPPA7Y6h4XewHoWaz8YEtDGId4X+AyKYl74uYRR7lhr2KnHyZXOpW/qqNJ1OzxqvrskkctotwsaYDlDw1TgFGgOcZmYDMzZ4wfE1w621Ig4Qfo3dNjRIiH7pUTrFyMJmfiz2r6TJfJCtadBr+HDUi2fNMfLl5+Ne/hp/2YjOfiAJmciKqAZbo88+SPJkwA3WluT0tBVD4couqG3tvEMzfUchPnQIVoFd0lRz1g43ThTVvV35tUW+KE6Qy7scgPwx8="
